name: Upload Python Package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Linux wheels (manylinux2014, Py 3.8–3.12) + sdist
        run: |
          docker run --rm -v "$PWD":/io -w /io quay.io/pypa/manylinux2014_x86_64 \
            /bin/bash -lc '
              set -euo pipefail
              unset LD_LIBRARY_PATH  # avoid leaking host libs
              curl -sSf https://sh.rustup.rs | sh -s -- -y
              source "$HOME/.cargo/env"
              # Build wheels for the manylinux-provided CPython versions
              for PY in cp38-cp38 cp39-cp39 cp310-cp310 cp311-cp311 cp312-cp312; do
                /opt/python/$PY/bin/python -m pip install -U pip maturin
                /opt/python/$PY/bin/maturin build --release --manylinux 2014 \
                  --interpreter /opt/python/$PY/bin/python
              done
              # Also produce a source distribution
              /opt/python/cp311-cp311/bin/python -m pip install -U pip maturin
              /opt/python/cp311-cp311/bin/maturin sdist
              # Optional: show audit info for sanity
              auditwheel show target/wheels/*.whl | sed -n "1,120p"
            '

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install -U twine
          twine upload --skip-existing target/wheels/* dist/*
